spring:
  application:
    name: stock-manage-service
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 数据库配置
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/stock
    username: stock_manage
    password: abcd123456
    druid:
      aop-patterns: com.jy.stock
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
      filters: stat,wall
      initial-size: 3
      max-active: 10
      max-wait: 60000
      min-idle: 3
      stat-view-servlet:
        enabled: true
        login-password: admin
        login-username: admin
        url-pattern: /druid/*
      web-stat-filter:
        enabled: true
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        session-stat-enable: true
        url-pattern: /*

  session:
    store-type: redis
  # REDIS
  redis:
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: abcd123456
    # 连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 60000
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 10000
  messages:
    basename: i18n/Messages
server:
  port: 8080
  servlet:
    context-path: /stock-manage-service/api

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 全局逻辑删除的实体字段名
      logic-delete-field: logic_delete
      logic-delete-value: true
      logic-not-delete-value: false